version: '3.8'

services:
  # PostgreSQL数据库服务（开发环境）
  db:
    image: postgres:15-alpine
    container_name: finance_app_db_dev
    environment:
      POSTGRES_DB: finance_app_dev
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - finance_network_dev

  # Django Web应用服务（开发环境）
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finance_app_web_dev
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-not-for-production
      - DATABASE_URL=postgresql://finance_user:finance_password@db:5432/finance_app_dev
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DJANGO_SETTINGS_MODULE=finance_project.settings
    volumes:
      - ./django_finance_app:/app
      - ./logs:/app/logs
    ports:
      - '8001:8000'
    depends_on:
      - db
    networks:
      - finance_network_dev
    restart: unless-stopped
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']

networks:
  finance_network_dev:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
