# Generated by Django 4.2.7 on 2025-08-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financerecord",
            name="process_type",
            field=models.CharField(
                choices=[("payment", "排单处理"), ("reimbursement", "报销处理")],
                default="payment",
                max_length=20,
                verbose_name="处理类型",
            ),
        ),
    ]
