# Generated by Django 4.2.7 on 2025-08-03 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance_app", "0002_financerecord_process_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="financerecord",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
    ]
