# Generated by Django 4.2.7 on 2025-08-02 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="uploads/", verbose_name="上传文件路径"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "output_file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="outputs/",
                        verbose_name="输出文件路径",
                    ),
                ),
                (
                    "output_filename",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="输出文件名"
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="处理记录数"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0.0, verbose_name="处理时间(秒)"),
                ),
            ],
            options={
                "verbose_name": "财务记录",
                "verbose_name_plural": "财务记录",
                "db_table": "finance_records",
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间戳"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        default="INFO", max_length=10, verbose_name="日志级别"
                    ),
                ),
                ("message", models.TextField(verbose_name="日志信息")),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="finance_app.financerecord",
                        verbose_name="财务记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理日志",
                "verbose_name_plural": "处理日志",
                "db_table": "processing_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
